import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Navigator } from '../components/Navigator'
import { Content } from '../components/Content'

export default function Home() {


  return (        
    <>
      <Head>
        <title>Book it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navigator />
        <Content />
      </main>
    </>
  )
}
