import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useMemo, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [title, setTitle] = useState<string>('Create Next App');

  useMemo(() => setTimeout(() => setTitle('test'), 1000), []);
    
  return (
    <>
      <Head>
        <title>Book it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
      </main>
    </>
  )
}
