export interface Appointment {
  id: string,
  userId: string,
  businessId: string,
  clientId: string,
  serviceId: string,
  startDate: number,
  endDate: number,
  serviceName: string,
  serviceDuration: number,
  serviceProvider: string,
  serviceCost: number,
  isVideo: boolean,
  isPaid: boolean,
};